% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Inference for categorical data},
  pdfauthor={Josh Iden},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Inference for categorical data}
\author{Josh Iden}
\date{}

\begin{document}
\maketitle

\hypertarget{getting-started}{%
\subsection{Getting Started}\label{getting-started}}

\hypertarget{load-packages}{%
\subsubsection{Load packages}\label{load-packages}}

In this lab, we will explore and visualize the data using the
\textbf{tidyverse} suite of packages, and perform statistical inference
using \textbf{infer}. The data can be found in the companion package for
OpenIntro resources, \textbf{openintro}.

Let's load the packages.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(openintro)}
\FunctionTok{library}\NormalTok{(infer)}
\end{Highlighting}
\end{Shaded}

\hypertarget{the-data}{%
\subsubsection{The data}\label{the-data}}

You will be analyzing the same dataset as in the previous lab, where you
delved into a sample from the Youth Risk Behavior Surveillance System
(YRBSS) survey, which uses data from high schoolers to help discover
health patterns. The dataset is called \texttt{yrbss}.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What are the counts within each category for the amount of days these
  students have texted while driving within the past 30 days?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{yrbss }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{count}\NormalTok{(text\_while\_driving\_30d, }\AttributeTok{sort=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 9 x 2
##   text_while_driving_30d     n
##   <chr>                  <int>
## 1 0                       4792
## 2 did not drive           4646
## 3 1-2                      925
## 4 <NA>                     918
## 5 30                       827
## 6 3-5                      493
## 7 10-19                    373
## 8 6-9                      311
## 9 20-29                    298
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  What is the proportion of people who have texted while driving every
  day in the past 30 days and never wear helmets?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{helms }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{select}\NormalTok{(}\DecValTok{8}\SpecialCharTok{:}\DecValTok{9}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(text\_while\_driving\_30d) }\SpecialCharTok{\&} 
\NormalTok{                helmet\_12m}\SpecialCharTok{==}\StringTok{"never"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{text =} \FunctionTok{ifelse}\NormalTok{(text\_while\_driving\_30d }\SpecialCharTok{==} \DecValTok{30}\NormalTok{, }\StringTok{"everyday"}\NormalTok{, }\StringTok{"other"}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{count}\NormalTok{(text)}

\NormalTok{helms}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 2
##   text         n
##   <chr>    <int>
## 1 everyday   463
## 2 other     6040
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{helms}\SpecialCharTok{$}\NormalTok{n[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(helms}\SpecialCharTok{$}\NormalTok{n)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.07119791
\end{verbatim}

463 out of 6503 text while driving every day and never wear helmets. The
proportion/probability is 0.071.

Remember that you can use \texttt{filter} to limit the dataset to just
non-helmet wearers. Here, we will name the dataset \texttt{no\_helmet}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(}\StringTok{\textquotesingle{}yrbss\textquotesingle{}}\NormalTok{, }\AttributeTok{package=}\StringTok{\textquotesingle{}openintro\textquotesingle{}}\NormalTok{)}
\NormalTok{no\_helmet }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(helmet\_12m }\SpecialCharTok{==} \StringTok{"never"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Also, it may be easier to calculate the proportion if you create a new
variable that specifies whether the individual has texted every day
while driving over the past 30 days or not. We will call this variable
\texttt{text\_ind}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{no\_helmet }\OtherTok{\textless{}{-}}\NormalTok{ no\_helmet }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{text\_ind =} \FunctionTok{ifelse}\NormalTok{(text\_while\_driving\_30d }\SpecialCharTok{==} \StringTok{"30"}\NormalTok{, }\StringTok{"yes"}\NormalTok{, }\StringTok{"no"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{inference-on-proportions}{%
\subsection{Inference on proportions}\label{inference-on-proportions}}

When summarizing the YRBSS, the Centers for Disease Control and
Prevention seeks insight into the population \emph{parameters}. To do
this, you can answer the question, ``What proportion of people in your
sample reported that they have texted while driving each day for the
past 30 days?'' with a statistic; while the question ``What proportion
of people on earth have texted while driving each day for the past 30
days?'' is answered with an estimate of the parameter.

The inferential tools for estimating population proportion are analogous
to those used for means in the last chapter: the confidence interval and
the hypothesis test.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{no\_helmet }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(text\_ind)) }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# filter out na\textquotesingle{}s}
  \FunctionTok{specify}\NormalTok{(}\AttributeTok{response =}\NormalTok{ text\_ind, }\AttributeTok{success =} \StringTok{"yes"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{generate}\NormalTok{(}\AttributeTok{reps =} \DecValTok{1000}\NormalTok{, }\AttributeTok{type =} \StringTok{"bootstrap"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"prop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{get\_ci}\NormalTok{(}\AttributeTok{level =} \FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   lower_ci upper_ci
##      <dbl>    <dbl>
## 1   0.0650   0.0773
\end{verbatim}

Note that since the goal is to construct an interval estimate for a
proportion, it's necessary to both include the \texttt{success} argument
within \texttt{specify}, which accounts for the proportion of non-helmet
wearers than have consistently texted while driving the past 30 days, in
this example, and that \texttt{stat} within \texttt{calculate} is here
``prop'', signaling that you are trying to do some sort of inference on
a proportion.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  What is the margin of error for the estimate of the proportion of
  non-helmet wearers that have texted while driving each day for the
  past 30 days based on this survey?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# M E = 1.96 × S E = 1.96 × p ( 1 − p ) / n }
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{1000}
\NormalTok{p }\OtherTok{\textless{}{-}}\NormalTok{ helms}\SpecialCharTok{$}\NormalTok{n[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(helms}\SpecialCharTok{$}\NormalTok{n) }
\NormalTok{ME }\OtherTok{\textless{}{-}} \FloatTok{1.96} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(p}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{p)}\SpecialCharTok{/}\NormalTok{n)}
\NormalTok{ME}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.01593864
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Using the \texttt{infer} package, calculate confidence intervals for
  two other categorical variables (you'll need to decide which level to
  call ``success'', and report the associated margins of error. Interpet
  the interval in context of the data. It may be helpful to create new
  data sets for each of the two countries first, and then use these data
  sets to construct the confidence intervals.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glimpse}\NormalTok{(yrbss)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 13,583
## Columns: 13
## $ age                      <int> 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, 1~
## $ gender                   <chr> "female", "female", "female", "female", "fema~
## $ grade                    <chr> "9", "9", "9", "9", "9", "9", "9", "9", "9", ~
## $ hispanic                 <chr> "not", "not", "hispanic", "not", "not", "not"~
## $ race                     <chr> "Black or African American", "Black or Africa~
## $ height                   <dbl> NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, 1~
## $ weight                   <dbl> NA, NA, 84.37, 55.79, 46.72, 67.13, 131.54, 7~
## $ helmet_12m               <chr> "never", "never", "never", "never", "did not ~
## $ text_while_driving_30d   <chr> "0", NA, "30", "0", "did not drive", "did not~
## $ physically_active_7d     <int> 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7, ~
## $ hours_tv_per_school_day  <chr> "5+", "5+", "5+", "2", "3", "5+", "5+", "5+",~
## $ strength_training_7d     <int> 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7, ~
## $ school_night_hours_sleep <chr> "8", "6", "<5", "6", "9", "8", "9", "6", "<5"~
\end{verbatim}

Let's calculate confidence intervals for sleep and hours of tv.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#students who sleep 8 hours or more}
\FunctionTok{unique}\NormalTok{(yrbss}\SpecialCharTok{$}\NormalTok{school\_night\_hours\_sleep)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "8"   "6"   "<5"  "9"   "10+" "7"   "5"   NA
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sleep }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(school\_night\_hours\_sleep)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{eight\_hours =} \FunctionTok{ifelse}\NormalTok{(school\_night\_hours\_sleep }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"8"}\NormalTok{,}\StringTok{"9"}\NormalTok{,}\StringTok{"10+"}\NormalTok{), }\StringTok{"yes"}\NormalTok{, }\StringTok{"no"}\NormalTok{))}

\NormalTok{sleep }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{count}\NormalTok{(eight\_hours) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{p =}\NormalTok{ n }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 3
##   eight_hours     n     p
##   <chr>       <int> <dbl>
## 1 no           8564 0.694
## 2 yes          3771 0.306
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sleep }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{specify}\NormalTok{(}\AttributeTok{response =}\NormalTok{ eight\_hours, }\AttributeTok{success =} \StringTok{"yes"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{generate}\NormalTok{(}\AttributeTok{reps =} \DecValTok{1000}\NormalTok{, }\AttributeTok{type =} \StringTok{"bootstrap"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"prop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{get\_ci}\NormalTok{(}\AttributeTok{level =} \FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   lower_ci upper_ci
##      <dbl>    <dbl>
## 1    0.297    0.314
\end{verbatim}

The 95\% confidence interval for the probability that a students gets at
least 8 hours of sleep is between 0.298-0.313.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#calculating margin of error}
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(sleep)}
\NormalTok{z }\OtherTok{\textless{}{-}} \FloatTok{1.96} \CommentTok{\# z{-}score 95\%}
\NormalTok{se }\OtherTok{\textless{}{-}}\NormalTok{ z}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{((p}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{p))}\SpecialCharTok{/}\NormalTok{n)}
\NormalTok{me }\OtherTok{\textless{}{-}}\NormalTok{ z}\SpecialCharTok{*}\NormalTok{se}
\NormalTok{me}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.008894833
\end{verbatim}

The margin of error is 0.0129

Let's look at hours of tv:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tv }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(hours\_tv\_per\_school\_day)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{five\_hours\_or\_more =} \FunctionTok{ifelse}\NormalTok{(hours\_tv\_per\_school\_day }\SpecialCharTok{==} \StringTok{"5+"}\NormalTok{, }\StringTok{"yes"}\NormalTok{,}\StringTok{"no"}\NormalTok{))}

\NormalTok{tv }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{count}\NormalTok{(five\_hours\_or\_more) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{p =}\NormalTok{ n }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 3
##   five_hours_or_more     n     p
##   <chr>              <int> <dbl>
## 1 no                 11650 0.880
## 2 yes                 1595 0.120
\end{verbatim}

Calculating the 95\% confidence interval

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tv }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{specify}\NormalTok{(}\AttributeTok{response =}\NormalTok{ five\_hours\_or\_more, }\AttributeTok{success =} \StringTok{"yes"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{generate}\NormalTok{(}\AttributeTok{reps =} \DecValTok{1000}\NormalTok{, }\AttributeTok{type =} \StringTok{"bootstrap"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"prop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{get\_ci}\NormalTok{(}\AttributeTok{level =} \FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   lower_ci upper_ci
##      <dbl>    <dbl>
## 1    0.115    0.126
\end{verbatim}

The 95\% confidence interval for the probability of a student watching
five or more hours of tv is 0.115-0.126.

Calculating margin of error:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(tv)}
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(tv}\SpecialCharTok{$}\NormalTok{five\_hours\_or\_more }\SpecialCharTok{==} \StringTok{"yes"}\NormalTok{)}\SpecialCharTok{/}\NormalTok{n}
\NormalTok{z }\OtherTok{\textless{}{-}} \FloatTok{1.96} \CommentTok{\# z{-}score 95\%}
\NormalTok{se }\OtherTok{\textless{}{-}}\NormalTok{ z}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{((p}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{p))}\SpecialCharTok{/}\NormalTok{n)}
\NormalTok{me }\OtherTok{\textless{}{-}}\NormalTok{ z}\SpecialCharTok{*}\NormalTok{se}
\NormalTok{me}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.01086369
\end{verbatim}

The margin of error is 0.0108

\hypertarget{how-does-the-proportion-affect-the-margin-of-error}{%
\subsection{How does the proportion affect the margin of
error?}\label{how-does-the-proportion-affect-the-margin-of-error}}

The difference between the upper CI and lower CI is 0.011, so the margin
of error is nearly equal to the distance between the upper and lower
CIs.

Imagine you've set out to survey 1000 people on two questions: are you
at least 6-feet tall? and are you left-handed? Since both of these
sample proportions were calculated from the same sample size, they
should have the same margin of error, right? Wrong! While the margin of
error does change with sample size, it is also affected by the
proportion.

Think back to the formula for the standard error:
\(SE = \sqrt{p(1-p)/n}\). This is then used in the formula for the
margin of error for a 95\% confidence interval:

\[
ME = 1.96\times SE = 1.96\times\sqrt{p(1-p)/n} \,.
\] Since the population proportion \(p\) is in this \(ME\) formula, it
should make sense that the margin of error is in some way dependent on
the population proportion. We can visualize this relationship by
creating a plot of \(ME\) vs.~\(p\).

Since sample size is irrelevant to this discussion, let's just set it to
some value (\(n = 1000\)) and use this value in the following
calculations:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{1000}
\end{Highlighting}
\end{Shaded}

The first step is to make a variable \texttt{p} that is a sequence from
0 to 1 with each number incremented by 0.01. You can then create a
variable of the margin of error (\texttt{me}) associated with each of
these values of \texttt{p} using the familiar approximate formula
(\(ME = 2 \times SE\)).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\AttributeTok{from =} \DecValTok{0}\NormalTok{, }\AttributeTok{to =} \DecValTok{1}\NormalTok{, }\AttributeTok{by =} \FloatTok{0.01}\NormalTok{)}
\NormalTok{me }\OtherTok{\textless{}{-}} \DecValTok{2} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(p }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ p)}\SpecialCharTok{/}\NormalTok{n)}
\end{Highlighting}
\end{Shaded}

Lastly, you can plot the two variables against each other to reveal
their relationship. To do so, we need to first put these variables in a
data frame that you can call in the \texttt{ggplot} function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dd }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{p =}\NormalTok{ p, }\AttributeTok{me =}\NormalTok{ me)}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ dd, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ p, }\AttributeTok{y =}\NormalTok{ me)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Population Proportion"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Margin of Error"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Lab6_inf_for_categorical_data_files/figure-latex/me-plot-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Describe the relationship between \texttt{p} and \texttt{me}. Include
  the margin of error vs.~population proportion plot you constructed in
  your answer. For a given sample size, for which value of \texttt{p} is
  margin of error maximized?
\end{enumerate}

\emph{The me increase as the popoulation proportion increases, and
decreases as the population proportion decreases}

\hypertarget{success-failure-condition}{%
\subsection{Success-failure condition}\label{success-failure-condition}}

We have emphasized that you must always check conditions before making
inference. For inference on proportions, the sample proportion can be
assumed to be nearly normal if it is based upon a random sample of
independent observations and if both \(np \geq 10\) and
\(n(1 - p) \geq 10\). This rule of thumb is easy enough to follow, but
it makes you wonder: what's so special about the number 10?

The short answer is: nothing. You could argue that you would be fine
with 9 or that you really should be using 11. What is the ``best'' value
for such a rule of thumb is, at least to some degree, arbitrary.
However, when \(np\) and \(n(1-p)\) reaches 10 the sampling distribution
is sufficiently normal to use confidence intervals and hypothesis tests
that are based on that approximation.

You can investigate the interplay between \(n\) and \(p\) and the shape
of the sampling distribution by using simulations. Play around with the
following app to investigate how the shape, center, and spread of the
distribution of \(\hat{p}\) changes as \(n\) and \(p\) changes.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\item
  Describe the sampling distribution of sample proportions at
  \(n = 300\) and \(p = 0.1\). Be sure to note the center, spread, and
  shape. \emph{The distribution appears normal, the center appears to be
  around 0.1, and spread from about 0.03 to 1.13}
\item
  Keep \(n\) constant and change \(p\). How does the shape, center, and
  spread of the sampling distribution vary as \(p\) changes. You might
  want to adjust min and max for the \(x\)-axis for a better view of the
  distribution.
\end{enumerate}

\emph{As p increase, the center increases, the spread stays consistent,
and the shape becomes right-skewed}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Now also change \(n\). How does \(n\) appear to affect the
  distribution of \(\hat{p}\)? \emph{As n increases, the spread
  decreases}
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{more-practice}{%
\subsection{More Practice}\label{more-practice}}

For some of the exercises below, you will conduct inference comparing
two proportions. In such cases, you have a response variable that is
categorical, and an explanatory variable that is also categorical, and
you are comparing the proportions of success of the response variable
across the levels of the explanatory variable. This means that when
using \texttt{infer}, you need to include both variables within
\texttt{specify}.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  Is there convincing evidence that those who sleep 10+ hours per day
  are more likely to strength train every day of the week? As always,
  write out the hypotheses for any tests you conduct and outline the
  status of the conditions for inference. If you find a significant
  difference, also quantify this difference with a confidence interval.
\end{enumerate}

\(H_{0}\): Null hypothesis: There is no evidence that those who sleep
10+ hours per day are more likely to strength train every day of the
week.

\(H_{A}\): Alternative hypothesis: There is evidence that those who
sleep 10+ hours per day are more likely to strength train every day of
the week.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{exercise }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(strength\_training\_7d)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{everyday =} \FunctionTok{ifelse}\NormalTok{(strength\_training\_7d }\SpecialCharTok{==} \StringTok{"7"}\NormalTok{, }\StringTok{"yes"}\NormalTok{, }\StringTok{"no"}\NormalTok{))}

\NormalTok{exercise }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{count}\NormalTok{(everyday) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{p =}\NormalTok{ n }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 3
##   everyday     n     p
##   <chr>    <int> <dbl>
## 1 no       10322 0.832
## 2 yes       2085 0.168
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{exercise }\SpecialCharTok{|\textgreater{}}
 \FunctionTok{specify}\NormalTok{(}\AttributeTok{response =}\NormalTok{ everyday, }\AttributeTok{success =} \StringTok{"yes"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
 \FunctionTok{generate}\NormalTok{(}\AttributeTok{reps =} \DecValTok{1000}\NormalTok{, }\AttributeTok{type =} \StringTok{"bootstrap"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
 \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"prop"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
 \FunctionTok{get\_ci}\NormalTok{(}\AttributeTok{level =} \FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   lower_ci upper_ci
##      <dbl>    <dbl>
## 1    0.162    0.175
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(exercise}\SpecialCharTok{$}\NormalTok{everyday }\SpecialCharTok{==} \StringTok{"yes"}\NormalTok{) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(exercise}\SpecialCharTok{$}\NormalTok{everyday }\SpecialCharTok{==} \StringTok{"yes"}\SpecialCharTok{|}\NormalTok{exercise}\SpecialCharTok{$}\NormalTok{everyday }\SpecialCharTok{==}  \StringTok{"no"}\NormalTok{)}
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(exercise)}
\NormalTok{z }\OtherTok{\textless{}{-}} \FloatTok{1.96}
\NormalTok{se }\OtherTok{\textless{}{-}}\NormalTok{ z}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{((p}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{p))}\SpecialCharTok{/}\NormalTok{n)}

\NormalTok{me}\OtherTok{\textless{}{-}}\NormalTok{ z }\SpecialCharTok{*}\NormalTok{ se}
\NormalTok{me}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.01289576
\end{verbatim}

Proportion of students training 7 days: 0.168 95\% Confidence Interval:
0.161, 0.174 ME: 0.01289

Now let's look at sleep 10+ hours

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sleep\_10 }\OtherTok{\textless{}{-}}\NormalTok{ yrbss }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(school\_night\_hours\_sleep)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{ten\_or\_more =} \FunctionTok{ifelse}\NormalTok{(school\_night\_hours\_sleep }\SpecialCharTok{==} \StringTok{"10+"}\NormalTok{, }\StringTok{"yes"}\NormalTok{, }\StringTok{"no"}\NormalTok{))}

\NormalTok{sleep\_10 }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{count}\NormalTok{(ten\_or\_more) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{p =}\NormalTok{ n }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 3
##   ten_or_more     n      p
##   <chr>       <int>  <dbl>
## 1 no          12019 0.974 
## 2 yes           316 0.0256
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sleep\_10 }\SpecialCharTok{|\textgreater{}}
 \FunctionTok{specify}\NormalTok{(}\AttributeTok{response =}\NormalTok{ ten\_or\_more, }\AttributeTok{success =} \StringTok{"yes"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
 \FunctionTok{generate}\NormalTok{(}\AttributeTok{reps =} \DecValTok{1000}\NormalTok{, }\AttributeTok{type =} \StringTok{"bootstrap"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
 \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"prop"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
 \FunctionTok{get\_ci}\NormalTok{(}\AttributeTok{level =} \FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   lower_ci upper_ci
##      <dbl>    <dbl>
## 1   0.0227   0.0284
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(sleep\_10}\SpecialCharTok{$}\NormalTok{ten\_or\_more }\SpecialCharTok{==} \StringTok{"yes"}\NormalTok{) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(sleep\_10}\SpecialCharTok{$}\NormalTok{ten\_or\_more }\SpecialCharTok{==} \StringTok{"yes"}\SpecialCharTok{|}\NormalTok{sleep\_10}\SpecialCharTok{$}\NormalTok{ten\_or\_more }\SpecialCharTok{==}  \StringTok{"no"}\NormalTok{)}
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(sleep\_10)}
\NormalTok{z }\OtherTok{\textless{}{-}} \FloatTok{1.96}
\NormalTok{se }\OtherTok{\textless{}{-}}\NormalTok{ z}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{((p}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{p))}\SpecialCharTok{/}\NormalTok{n)}

\NormalTok{me}\OtherTok{\textless{}{-}}\NormalTok{ z }\SpecialCharTok{*}\NormalTok{ se}
\NormalTok{me}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.005464886
\end{verbatim}

Proportion of students sleeping 10+ hours: 0.0256 95\% Confidence
Interval: 0.0229, 0.0285 ME: 0.005464

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\tightlist
\item
  Let's say there has been no difference in likeliness to strength train
  every day of the week for those who sleep 10+ hours. What is the
  probablity that you could detect a change (at a significance level of
  0.05) simply by chance? \emph{Hint:} Review the definition of the Type
  1 error.
\end{enumerate}

\emph{The probability of making a Type I error is equal to the level of
significance, so the probability is 5\%}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{10}
\tightlist
\item
  Suppose you're hired by the local government to estimate the
  proportion of residents that attend a religious service on a weekly
  basis. According to the guidelines, the estimate must have a margin of
  error no greater than 1\% with 95\% confidence. You have no idea what
  to expect for \(p\). How many people would you have to sample to
  ensure that you are within the guidelines?\\
  \emph{Hint:} Refer to your plot of the relationship between \(p\) and
  margin of error. This question does not require using a dataset.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ME }\OtherTok{\textless{}{-}} \FloatTok{0.01} \CommentTok{\#margin of error}
\NormalTok{z }\OtherTok{\textless{}{-}} \FloatTok{1.96} \CommentTok{\#z{-}score for 95\% confidence}

\NormalTok{p }\OtherTok{\textless{}{-}} \FloatTok{0.5} \CommentTok{\#margin for error is highest at .5 of the population proportion}

\NormalTok{n }\OtherTok{\textless{}{-}}\NormalTok{ z}\SpecialCharTok{**}\DecValTok{2} \SpecialCharTok{*}\NormalTok{ p}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{p)}\SpecialCharTok{/}\NormalTok{ME}\SpecialCharTok{**}\DecValTok{2}
\NormalTok{n}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9604
\end{verbatim}

\emph{At least 9604 people}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\end{document}
